{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-chiron
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "chiron.name" . }}
    chart: {{ template "chiron.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    istio: chiron
spec:
{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
{{ include "podDisruptionBudget.spec" .Values.global.defaultPodDisruptionBudget }}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "chiron.name" . }}
      release: {{ .Release.Name }}
      istio: chiron
{{- end }}
