apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: web
    istio-injection: enabled
spec:
  containers:
    - name: front-end
      image: nginx
      ports:
        - containerPort: 80