apiVersion: v1
kind: Service
metadata:
  name: protomutate
  namespace: proto
  labels:
    app: protomutate
spec:
  ports:
    - port: 443
      name: https-validation
  selector:
    app: protomutate