# FROM scratch
FROM istionightly/base_debug

# obtained from debian ca-certs deb using fetch_cacerts.sh
ADD ca-certificates.tgz /
# All containers need a /tmp directory
WORKDIR /tmp/
ADD protovalidate /usr/local/bin/protovalidate

ENTRYPOINT [ "/usr/local/bin/protovalidate", "--log_output_level", "default:debug" ]
